# Generated by Django 5.0.6 on 2024-05-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watch',
            new_name='clothe',
        ),
    ]
