# Generated by Django 5.0.6 on 2024-05-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_watch_review_clothe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
